#!bash

# Aliases -- These are sourced in .profile

alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias l.='ls -d .*'
alias ls='ls --color=auto'

alias dspurge='find . -name .DS_Store -delete'
alias vipr='vi ~/.profile'
alias vial='vi ~/.aliases'
alias bc='bc -l'
alias which='alias | /usr/local/bin/gwhich --tty-only --read-alias --show-dot --show-tilde'
alias find='gfind'

# Functions -- Slightly longer things than aliases

if [ -f "/usr/libexec/java_home" ]; then
    # Sets the version to the specified version
    # Kind of actually just a glorified alias to /usr/libexed/java_home
    # use -v <version> to set the version to the specified version
    function jhome () {
        export JAVA_HOME=`/usr/libexec/java_home $@`
        echo "JAVA_HOME:" $JAVA_HOME
        echo "java -version:"
        java -version
    }
fi

# Sets up an eclipse workspace
# First the workspace must exist then run this command from the 
# root directory of the workspace
# The settings folder of the workspace will be deleted and symlinked to
# The template workspace at ~/.templates/eclipse
function eclset () {
    present_dir=`pwd`
    cd  $1/.metadata/.plugins/org.eclipse.core.runtime
    rm -rf .settings
    ln -s ~/.templates/eclipse/.metadata/.plugins/org.eclipse.core.runtime/.settings .settings
    cd $present_dir
}
