# Brew
brew 'bash'
brew 'zsh'
brew 'the_silver_searcher'
brew 'wget'
brew 'tree'
brew 'coreutils'
brew 'git'
tap 'universal-ctags/universal-ctags'
brew 'universal-ctags'
brew 'shellcheck'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'python'
brew 'vim', args: %w[--with-override-system-vi]
tap 'neovim/homebrew-neovim'
brew 'neovim'
brew 'p7zip'
brew 'unar'
brew 'ssh-copy-id'
brew 'opam'
brew 'haskell-stack'


tap 'Homebrew/homebrew-completions'
brew 'bash-completion'
brew 'zsh-completions'
brew 'vagrant-completion' # for cask 'vagrant'

# Cask
cask 'google-chrome'
cask 'dropbox'
cask 'eclipse-java'
cask 'vagrant'
cask 'iterm2'
cask 'quicksilver'
cask '1password'
cask 'xquartz'

# Quicklook -- make quicklook better / more useful
cask 'qlstephen'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
