#!/bin/bash
# Install script to set up a general unix / linux capable computer as a
# development machine
#
# Does all nescessary configuration and also sources any script in
# install.d/*.auto.sh

if [ $(uname) == "Darwin" ]; then
    DARWIN=1
fi

if [ -n "$DARWIN" ]; then
    source "$HOME/.dotfiles/install.d/brew.sh"
fi

source "$HOME/.dotfiles/install.d/link.sh"

if [ -n "$DARWIN" ]; then
    source "$HOME/.dotfiles/install.d/osx.sh"
fi

if test $(find ~/.dotfiles/install.d -name "*.sh.auto"); then
    for i in $HOME/.dotfiles/install.d/*.sh.auto; do
        source "$i"
    done
fi
