# This is the predecessor of starship.toml to be used with my config. When
# making changes you should compile using ./build-starship.sh (located in the
# same directory as this file.

#IF SUPPORTS(RIGHT_PROMPT)

# left side only has prompt char; extra things go on right
format = "$character"
right_format = "$jobs$shlvl $all"

#ELSE - OTHER SHELLS

# for shells where we don't have a right prompt use something pretty close to
# starship default
format = "$jobs$shlvl $all$line_break$character"

#END IF
command_timeout = 20 # prompt must be very fast; git_status ruins this most often
add_newline = false

# disable a bunch of stuff that I don't care very much about
# Rant: I don't really understand why it is popular to know what
# compiler/language version is being used at all times, if you are in a context
# where that is important you're doing something wrong because your package
# manager isn't managing the version of your compiler for you.
c.disabled = true
cmake.disabled = true
cobol.disabled = true
conda.disabled = true
crystal.disabled = true
dart.disabled = true
deno.disabled = true
dotnet.disabled = true
elixir.disabled = true
elm.disabled = true
erlang.disabled = true
golang.disabled = true
haskell.disabled = true
helm.disabled = true
java.disabled = true
julia.disabled = true
kotlin.disabled = true
lua.disabled = true
nim.disabled = true
nodejs.disabled = true
ocaml.disabled = true
openstack.disabled = true
package.disabled = true
perl.disabled = true
php.disabled = true
pulumi.disabled = true
purescript.disabled = true
python.disabled = true
red.disabled = true
rlang.disabled = true
ruby.disabled = true
rust.disabled = true
scala.disabled = true
singularity.disabled = true
swift.disabled = true
terraform.disabled = true
vagrant.disabled = true
vlang.disabled = true
zig.disabled = true

[directory]
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold purple"

[git_branch]
only_attached = true

[git_commit]
style = "bold purple" # make color the same as git_branch
tag_disabled = false
tag_symbol = " @ "

[git_status]
# disabled stashed; I don't care about knowing if I have a stash; either they're
# old and stale or I get rid of them almost immediately
stashed = ""
# Really, I want to be able to replicate something similar to the old behavior
# where I just have a dirty/staged indicator.
# contemplate going back to this symbol
# modified = "●"


# the defaults here are quite a bit too verbose IMO
[git_state]
rebase = "R"
merge = "M"
revert = "REV"
cherry_pick = "CP"
bisect = "B"
am_or_rebase = "R/AM"

[jobs]
symbol = "⚙"

[memory_usage]
threshold = 90
format = "[${ram}( | ${swap})]($style) "
style = "bold dimmed magenta"
disabled = false

[shlvl]
symbol = "🪺"
format = "[$symbol]($style)"
disabled = false

[time]
disabled = false
